[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."scheduled-publisher"]
  schedule = "*/1 * * * *"

[functions."cron-scheduler"]
  schedule = "*/1 * * * *"
