
const $=id=>document.getElementById(id);
let state={loggedIn:false,accounts:[],originals:[],edited:[],queue:[],settings:{cloudName:"",uploadPreset:"",hookFontSize:54,hookTop:90,hookDuration:4,postsPerDay:3,publishTimes:["08:00","14:00","20:00"],scheduleStart:new Date().toISOString().slice(0,10)}};
const STORE="marrsile_clean_hook_pipeline_v1";
const hooks=["هذا العطر خطير بصراحة 😮","إذا تحب الفخامة هذا لك","الناس صارت تسأل عنه كثير","العطر اللي يثبت حضورك","من أول رشة بتحس بالفرق","هذا مو إعلان عادي 😉","ريحته فخمة بشكل مو طبيعي","العرض هذا ما يتفوت","اختيار قوي لعشاق الفخامة","العطر اللي ينقص مجموعتك","ريحة تعطيك ثقة طول اليوم","فخامة الخليج تبدأ من هنا","العطر اللي يخليك مميز","جربه مرة وبتفهم السر","هذا أكثر عطر عليه طلب"];
function save(){try{localStorage.setItem(STORE,JSON.stringify(state))}catch(e){console.error(e)}}
function load(){try{const s=JSON.parse(localStorage.getItem(STORE)||"null"); if(s) state={...state,...s,settings:{...state.settings,...(s.settings||{})}}}catch(e){}}
function functionsBase(){return "/.netlify/functions"}
async function parseJson(res){const t=await res.text();try{return JSON.parse(t)}catch(e){throw new Error("Non JSON: "+t.slice(0,120))}}
function msg(t){alert(t)}
function pickHook(n){const seed=String(n||Date.now()).split("").reduce((a,c)=>a+c.charCodeAt(0),0);return hooks[seed%hooks.length]}
function switchTab(tab){document.querySelectorAll(".nav").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));document.querySelectorAll(".tab").forEach(s=>s.classList.toggle("active",s.id===tab))}
function render(){ $("loginView").classList.toggle("hidden",state.loggedIn); $("appView").classList.toggle("hidden",!state.loggedIn); $("statAccounts").textContent=state.accounts.length;$("statOriginals").textContent=state.originals.length;$("statEdited").textContent=state.edited.length;$("statQueue").textContent=state.queue.length; $("cloudName").value=state.settings.cloudName||"";$("uploadPreset").value=state.settings.uploadPreset||"";$("hookFontSize").value=state.settings.hookFontSize;$("hookTop").value=state.settings.hookTop;$("hookDuration").value=state.settings.hookDuration;$("postsPerDay").value=state.settings.postsPerDay;$("publishTimes").value=state.settings.publishTimes.join(",");$("scheduleStart").value=state.settings.scheduleStart; renderAccounts();renderOriginals();renderEdited();renderQueue();}
function renderAccounts(){$("accountsList").innerHTML=state.accounts.length?state.accounts.map(a=>`<div class="account-card"><b>${a.name||a.username||"Instagram"}</b><div>@${String(a.username||a.user||"").replace("@","")}</div><span class="badge ok">Officially Connected</span></div>`).join(""):"<p>لا توجد حسابات.</p>"}
function renderOriginals(){$("originalVideos").innerHTML=state.originals.map((v,i)=>`<div class="video-card"><video src="${v.localUrl}" controls muted></video><h4>${v.name}</h4><span class="badge warn">أصلي - لا ينشر</span>${v.rendered?'<span class="badge ok">تم تعديله</span>':""}<div class="actions"><button class="primary" onclick="renderOne(${i})">تعديل بالهوك</button><button class="danger" onclick="deleteOriginal(${i})">حذف</button></div></div>`).join("")||"<p>ارفع الفيديوهات الأصلية.</p>"}
function renderEdited(){$("editedVideos").innerHTML=state.edited.map((v,i)=>`<div class="video-card"><video src="${v.cloudinaryUrl||v.localUrl}" controls></video><h4>${v.name}</h4><div class="hook-label">${v.hook}</div>${v.cloudinaryUrl?'<span class="badge ok">Cloudinary ✅</span>':'<span class="badge warn">قيد الرفع</span>'}<div class="actions"><button class="primary" onclick="publishEdited(${i})">نشر الآن</button><button class="secondary" onclick="scheduleEdited(${i})">جدولة</button><button class="danger" onclick="deleteEdited(${i})">حذف</button></div></div>`).join("")||"<p>لا توجد فيديوهات معدلة.</p>"}
function renderQueue(){$("queueList").innerHTML=state.queue.map((q,i)=>`<div class="queue-card"><div><b>${q.videoName}</b><div>${q.accountName}</div><span class="badge ok">${q.scheduledDate} ${q.scheduledTime}</span></div><div class="actions"><button class="primary" onclick="publishQueueItem(${i})">نشر الآن</button><button class="danger" onclick="deleteQueueItem(${i})">حذف</button></div></div>`).join("")||"<p>لا توجد جدولة.</p>"}
function fileObj(f){return{id:"o_"+Date.now()+"_"+Math.random().toString(16).slice(2),name:f.name,size:f.size,type:f.type,file:f,localUrl:URL.createObjectURL(f),rendered:false}}
function round(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function wrap(ctx,text,max){const words=String(text).split(/\s+/),lines=[];let line="";for(const w of words){const t=line?line+" "+w:w;if(ctx.measureText(t).width>max&&line){lines.push(line);line=w}else line=t}if(line)lines.push(line);return lines.slice(0,3)}
async function renderVideo(original){const file=original.file;if(!file)throw new Error("الفيديو الأصلي غير متاح بعد تحديث الصفحة، أعد رفعه للتعديل.");const hook=pickHook(file.name);const s=state.settings;return new Promise((resolve,reject)=>{const video=document.createElement("video");video.muted=true;video.playsInline=true;video.src=URL.createObjectURL(file);video.onloadedmetadata=async()=>{try{const c=document.createElement("canvas");c.width=video.videoWidth||1080;c.height=video.videoHeight||1920;const ctx=c.getContext("2d");const stream=c.captureStream(30);const mime=["video/webm;codecs=vp9","video/webm;codecs=vp8","video/webm"].find(t=>MediaRecorder.isTypeSupported(t))||"video/webm";const rec=new MediaRecorder(stream,{mimeType:mime});const chunks=[];rec.ondataavailable=e=>{if(e.data&&e.data.size)chunks.push(e.data)};rec.onstop=()=>{URL.revokeObjectURL(video.src);resolve({blob:new Blob(chunks,{type:mime}),hook,mime})};let start=performance.now();function frame(){if(video.ended||video.paused){try{rec.stop()}catch(e){};return}const w=c.width,h=c.height;ctx.drawImage(video,0,0,w,h);if((performance.now()-start)/1000<=Number(s.hookDuration||4)){const fs=Math.max(28,Math.round((w/1080)*Number(s.hookFontSize||54)));ctx.font=`900 ${fs}px Arial`;ctx.textAlign="center";ctx.textBaseline="middle";const lines=wrap(ctx,hook,w*.86),lh=fs*1.22,px=fs*.65,py=fs*.45;const tw=Math.min(w*.86,Math.max(...lines.map(l=>ctx.measureText(l).width),200));const bw=tw+px*2,bh=lines.length*lh+py*2,x=(w-bw)/2,y=Number(s.hookTop||90);ctx.fillStyle="rgba(0,0,0,.72)";round(ctx,x,y,bw,bh,Math.round(fs*.35));ctx.fill();ctx.strokeStyle="rgba(255,255,255,.35)";ctx.lineWidth=2;round(ctx,x,y,bw,bh,Math.round(fs*.35));ctx.stroke();ctx.fillStyle="#fff";ctx.shadowColor="rgba(0,0,0,.75)";ctx.shadowBlur=18;ctx.shadowOffsetY=5;lines.forEach((line,idx)=>ctx.fillText(line,w/2,y+py+(idx+.5)*lh));ctx.shadowBlur=0}requestAnimationFrame(frame)}rec.start(1000);await video.play();frame()}catch(e){reject(e)}};video.onerror=()=>reject(new Error("فشل قراءة الفيديو"))})}
async function uploadCloudinary(file){const {cloudName,uploadPreset}=state.settings;if(!cloudName||!uploadPreset)throw new Error("أدخل Cloudinary في الإعدادات.");const fd=new FormData();fd.append("file",file);fd.append("upload_preset",uploadPreset);fd.append("folder","marrsile-hooked-reels");const res=await fetch(`https://api.cloudinary.com/v1_1/${cloudName}/video/upload`,{method:"POST",body:fd});const data=await res.json();if(!res.ok)throw new Error(JSON.stringify(data));return data}
async function renderOne(i){const original=state.originals[i];if(!original)return;$("renderProgress").textContent=`جاري تعديل: ${original.name}`;try{const r=await renderVideo(original);const final=new File([r.blob],original.name.replace(/\.[^.]+$/,"")+"_hooked.webm",{type:r.mime});const ed={id:"e_"+Date.now(),name:final.name,hook:r.hook,localUrl:URL.createObjectURL(final),cloudinaryUrl:"",status:"uploading"};state.edited.push(ed);original.rendered=true;save();render();$("renderProgress").textContent="جاري رفع Cloudinary";const up=await uploadCloudinary(final);ed.cloudinaryUrl=up.secure_url;ed.publicId=up.public_id;ed.status="ready";save();render();$("renderProgress").textContent=`تم تجهيز: ${ed.name}`}catch(e){$("renderProgress").textContent="فشل: "+(e.message||e);msg($("renderProgress").textContent)}}
async function renderAll(){for(let i=0;i<state.originals.length;i++){if(!state.originals[i].rendered)await renderOne(i)}}
async function publishObj(v){const acc=state.accounts[0];if(!acc)throw new Error("لا يوجد حساب مربوط.");if(!v.cloudinaryUrl)throw new Error("الفيديو غير مرفوع إلى Cloudinary.");const create=await fetch(functionsBase()+"/publish-reel",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({accountId:acc.id||acc.instagramId,videoUrl:v.cloudinaryUrl,caption:v.hook||""})});const cr=await parseJson(create);if(!create.ok)throw new Error(JSON.stringify(cr));for(let n=0;n<16;n++){await new Promise(r=>setTimeout(r,n?12000:25000));const fin=await fetch(functionsBase()+"/publish-complete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({accountId:acc.id||acc.instagramId,creationId:cr.creationId})});const done=await parseJson(fin);if(fin.ok&&done.ok)return done;if(fin.status===202||done.retry)continue;throw new Error(JSON.stringify(done))}throw new Error("Instagram لم يجهز الفيديو.")}
async function publishEdited(i){try{msg("بدأ النشر...");await publishObj(state.edited[i]);msg("تم النشر بنجاح")}catch(e){msg("فشل النشر: "+(e.message||e))}}
function nextSlot(index){const per=Number(state.settings.postsPerDay||3),times=state.settings.publishTimes,day=Math.floor(index/per),slot=index%per;const d=new Date(state.settings.scheduleStart+"T00:00:00");d.setDate(d.getDate()+day);return{scheduledDate:d.toISOString().slice(0,10),scheduledTime:times[slot%times.length]||"08:00"}}
function scheduleEdited(i){const v=state.edited[i];const acc=state.accounts[0]||{name:"Instagram"};const s=nextSlot(state.queue.length);state.queue.push({...s,id:"q_"+Date.now(),videoName:v.name,videoUrl:v.cloudinaryUrl,hook:v.hook,accountId:acc.id||acc.instagramId,accountName:acc.name||acc.username||"Instagram"});save();render()}
function scheduleAll(){state.edited.forEach((v,i)=>{if(!state.queue.some(q=>q.videoName===v.name))scheduleEdited(i)});save();render()}
async function publishQueueItem(i){try{const q=state.queue[i];await publishObj({cloudinaryUrl:q.videoUrl,hook:q.hook});q.status="published";save();render();msg("تم النشر")}catch(e){msg("فشل النشر: "+(e.message||e))}}
function deleteQueueItem(i){if(confirm("حذف من الجدولة؟")){state.queue.splice(i,1);save();render()}}
function deleteOriginal(i){if(confirm("حذف؟")){state.originals.splice(i,1);save();render()}}
function deleteEdited(i){if(confirm("حذف؟")){state.edited.splice(i,1);save();render()}}
function clearQueue(){if(confirm("حذف كل الجدولة؟")){state.queue=[];save();render()}}
function clearOriginals(){if(confirm("حذف كل الأصلية؟")){state.originals=[];save();render()}}
function clearEdited(){if(confirm("حذف كل المعدلة؟")){state.edited=[];save();render()}}
async function loadAccounts(){try{const res=await fetch(functionsBase()+"/accounts");const data=await parseJson(res);if(!res.ok)throw new Error(JSON.stringify(data));state.accounts=(data.accounts||[]).map(a=>({...a,official:true}));save();render();msg("تم تحديث الحسابات")}catch(e){msg("فشل الحسابات: "+(e.message||e))}}
function bind(){document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$("loginBtn").onclick=()=>{state.loggedIn=true;save();render()};$("logoutBtn").onclick=()=>{state.loggedIn=false;save();render()};$("connectInstagramBtn").onclick=()=>location.href=functionsBase()+"/auth-instagram";$("reloadAccountsBtn").onclick=loadAccounts;$("saveStorageBtn").onclick=()=>{state.settings.cloudName=$("cloudName").value.trim();state.settings.uploadPreset=$("uploadPreset").value.trim();save();msg("تم الحفظ")};$("saveHookBtn").onclick=()=>{state.settings.hookFontSize=Number($("hookFontSize").value)||54;state.settings.hookTop=Number($("hookTop").value)||90;state.settings.hookDuration=Number($("hookDuration").value)||4;save();msg("تم الحفظ")};$("saveScheduleBtn").onclick=()=>{state.settings.postsPerDay=Number($("postsPerDay").value)||3;state.settings.publishTimes=$("publishTimes").value.split(",").map(x=>x.trim()).filter(Boolean);state.settings.scheduleStart=$("scheduleStart").value||new Date().toISOString().slice(0,10);save();msg("تم الحفظ")};$("videoInput").onchange=e=>{Array.from(e.target.files||[]).filter(f=>f.type.startsWith("video/")).forEach(f=>state.originals.push(fileObj(f)));save();render();e.target.value=""};$("renderAllBtn").onclick=renderAll;$("clearOriginalsBtn").onclick=clearOriginals;$("clearEditedBtn").onclick=clearEdited;$("scheduleAllEditedBtn").onclick=scheduleAll;$("rebuildQueueBtn").onclick=scheduleAll;$("clearQueueBtn").onclick=clearQueue}
load();bind();render();if(new URLSearchParams(location.search).get("connected")){loadAccounts();history.replaceState({},"",location.pathname)}setInterval(save,2000);
